// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';

export default {
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: 'file:./prisma/dev.db',
  },
};
